"""
Django settings for wedding_project project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os # Make sure os is imported at the top
from django.utils.translation import gettext_lazy as _
import dj_database_url
from pathlib import Path
import dotenv # Import dotenv to load local .env file

# Load environment variables from .env file (if it exists)
dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Reads from .env or environment, falls back to insecure default for dev
SECRET_KEY = os.environ.get('SECRET_KEY','django-insecure-at@6r*k2s1sbfl8p6&=719^!)*nwuwrf9v$4sj+)8a&78@pkb2')

# If 'RENDER' is set, we are live, so Debug is False. Otherwise True.
#DEBUG = 'RENDER' not in os.environ
DEBUG = True

# Allow the server URL to access the app
ALLOWED_HOSTS = []
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    # 'invapp' must be ABOVE 'allauth' to override templates
    'invapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'djstripe', # Commented out as we are using direct integration
    # Add these new apps for allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    #'django_extensions',

    # Add the specific providers you want to use
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'wedding_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'invapp.context_processors.add_active_plan_to_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'wedding_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        # Uses PostgreSQL on Render, falls back to SQLite locally
        default='sqlite:///' + os.path.join(BASE_DIR, 'db.sqlite3'),
        conn_max_age=600
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ro' # Set Romanian as the default language

LANGUAGES = [
    ('ro', _('Romanian')),
    ('en', _('English')),
]

TIME_ZONE = 'Europe/Bucharest' # Set to your local timezone

USE_I18N = True # Enable the translation system

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# This tells Django where to collect files for the server
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# This tells Django where to look for your local files
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Enable WhiteNoise compression
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Change from 'CompressedManifestStaticFilesStorage' to this:
  STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'invapp:dashboard' # Use the URL name defined in invapp/urls.py

# Redirect to home page after logout
LOGOUT_REDIRECT_URL = '/'

# Email Backend Configuration for Development
# This will print emails to the console/terminal instead of sending them.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@invapp.com' # The "from" address for your emails

# --- ADD THESE LINES AT THE BOTTOM ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Required for django-allauth
AUTHENTICATION_BACKENDS = [
    # Needed to log in by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Required by django.contrib.sites
SITE_ID = 1

# --- Allauth Specific Settings ---

# URL to redirect to after a successful login
LOGIN_REDIRECT_URL = '/dashboard/'

# --- CRITICAL FIX FOR REDIRECTS ---
# We disable the new 'ACCOUNT_LOGIN_METHODS' because it triggers passwordless flows.
# We use the explicit legacy settings to force Email+Password.

# ACCOUNT_LOGIN_METHODS = {'email'}  <-- COMMENTED OUT TO FIX REDIRECT
# ACCOUNT_SIGNUP_FIELDS = ['email*', 'first_name', 'last_name'] <-- COMMENTED OUT

# 1. Force standard password login
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_PASSWORD_REQUIRED = True

# 2. Explicitly DISABLE "Magic Code" / Passwordless Login
ACCOUNT_LOGIN_BY_CODE_ENABLED = False

# 3. Disable Verification for Development to allow instant login
ACCOUNT_EMAIL_VERIFICATION = 'none'

LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# --- ACCOUNT FORMS ---
# Ensure this is commented out so we don't use the broken CustomSignupForm
# ACCOUNT_FORMS = {
#    'signup': 'invapp.forms.CustomSignupForm',
# }

# ==========================================================
# === STRIPE CONFIGURATION (SECURED)                     ===
# ==========================================================

# We use os.environ.get to read from the .env file or the Server's settings
STRIPE_LIVE_SECRET_KEY = os.environ.get("STRIPE_LIVE_SECRET_KEY", "")

# NOTICE: The actual 'sk_test_...' string is GONE from here. GitHub will be happy.
# FIX: Added these lines so STRIPE_TEST_SECRET_KEY is explicitly defined before use
STRIPE_TEST_SECRET_KEY = os.environ.get("STRIPE_TEST_SECRET_KEY", "")
STRIPE_TEST_PUBLISHABLE_KEY = os.environ.get("STRIPE_TEST_PUBLISHABLE_KEY", "")
STRIPE_LIVE_PUBLISHABLE_KEY = os.environ.get("STRIPE_LIVE_PUBLISHABLE_KEY", "")

STRIPE_TEST_MODE = True

if STRIPE_TEST_MODE:
    STRIPE_SECRET_KEY = STRIPE_TEST_SECRET_KEY
    STRIPE_PUBLIC_KEY = STRIPE_TEST_PUBLISHABLE_KEY
else:
    STRIPE_SECRET_KEY = STRIPE_LIVE_SECRET_KEY
    STRIPE_PUBLIC_KEY = STRIPE_LIVE_PUBLISHABLE_KEY

STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")
DOMAIN_URL = 'http://127.0.0.1:8000' # You will change this on Render later