# Generated by Django 5.1.7 on 2025-07-16 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('preview_image_path', models.CharField(blank=True, help_text='Path to preview image in static files', max_length=255, null=True)),
                ('template_name', models.CharField(help_text="e.g., 'invapp/invites/design_classic.html'", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('baptism', 'Baptism')], default='wedding', help_text='The type of event being planned.', max_length=10)),
                ('child_name', models.CharField(blank=True, help_text='Name of the child (for baptism).', max_length=200)),
                ('parents_names', models.CharField(blank=True, help_text='Names of the parents (for baptism).', max_length=200)),
                ('bride_name', models.CharField(blank=True, help_text='Name of the bride.', max_length=100)),
                ('groom_name', models.CharField(blank=True, help_text='Name of the groom.', max_length=100)),
                ('bride_parents', models.CharField(blank=True, help_text="Names of the bride's parents (e.g., 'John & Jane Doe').", max_length=200)),
                ('groom_parents', models.CharField(blank=True, help_text="Names of the groom's parents (e.g., 'George & Mary Smith').", max_length=200)),
                ('godparents_names', models.CharField(blank=True, help_text='Names of the godparents (for baptism or wedding).', max_length=200)),
                ('title', models.CharField(default='Our Wedding', max_length=200)),
                ('date_time', models.DateTimeField(help_text='Date and time of the event')),
                ('venue_name', models.CharField(help_text='Name of the venue', max_length=200)),
                ('venue_address', models.TextField(help_text='Full address of the venue')),
                ('ceremony_time', models.TimeField(blank=True, help_text='Time of the religious ceremony (for baptism/wedding).', null=True)),
                ('ceremony_location', models.CharField(blank=True, help_text='Name and address of the church/ceremony location.', max_length=255)),
                ('Maps_embed_url', models.URLField(blank=True, help_text='Optional: Google Maps Embed SRC URL', max_length=1000, null=True)),
                ('calendar_description', models.TextField(blank=True, help_text='Optional: Short description for calendar event', null=True)),
                ('invitation_wording', models.TextField(blank=True, help_text="Main invitation text (e.g., 'Together with their families...')")),
                ('schedule_details', models.TextField(blank=True, help_text='Details about the schedule (e.g., Ceremony, Reception times)')),
                ('other_info', models.TextField(blank=True, help_text='Other information (e.g., Dress code, Gift registry)')),
                ('couple_photo', models.ImageField(blank=True, help_text='A photo of the couple to be displayed on the invitation.', null=True, upload_to='event_photos/')),
                ('landscape_photo', models.ImageField(blank=True, help_text='Optional: A landscape-oriented photo to display after the greeting (e.g., a photo of the venue or couple).', null=True, upload_to='event_landscape_photos/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('selected_design', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='invapp.carddesign')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Primary name for the invitation (e.g., 'The Smith Family', 'John Doe')", max_length=200)),
                ('email', models.EmailField(blank=True, help_text='Optional: Used for sending updates', max_length=254, null=True)),
                ('max_attendees', models.PositiveIntegerField(default=1, help_text='How many people are included in this invitation')),
                ('phone_number', models.CharField(blank=True, help_text="Optional: Guest's phone number.", max_length=30, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('couple', 'Couple'), ('family', 'Family'), ('other', 'Other / Prefer not to say')], default='other', help_text="Select the guest's gender or type for addressing the invitation.", max_length=20)),
                ('invitation_method', models.CharField(choices=[('digital', 'Digital Invitation'), ('physical', 'Physical Invitation')], default='digital', help_text='How will this guest receive their invitation?', max_length=10)),
                ('manual_is_attending', models.BooleanField(blank=True, help_text='Manually set attendance status (e.g., for physical RSVPs).', null=True)),
                ('manual_attending_count', models.PositiveIntegerField(blank=True, help_text='Manually set number of attendees if known (especially for physical RSVPs).', null=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="Unique identifier for the guest's invitation link", unique=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='invapp.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], help_text='Will they attend?', null=True)),
                ('number_attending', models.PositiveIntegerField(blank=True, help_text='How many are actually coming?', null=True)),
                ('meal_preference', models.CharField(blank=True, help_text='e.g., Vegetarian, Allergies', max_length=200, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional message from the guest', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rsvp_details', to='invapp.guest')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField(default=8)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='invapp.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('event', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TableAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invapp.guest')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_guests', to='invapp.table')),
            ],
            options={
                'unique_together': {('guest', 'table')},
            },
        ),
    ]
