# Generated by Django 5.1.7 on 2025-07-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='godparents_names',
        ),
    ]
