# Generated by Django 5.1.7 on 2025-07-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0002_remove_event_godparents_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='godparents_names',
            field=models.CharField(blank=True, help_text='Names of the godparents (for baptism or wedding).', max_length=200),
        ),
    ]
