# Generated by Django 5.1.7 on 2025-07-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0003_event_godparents_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='main_invitation_image',
            field=models.ImageField(blank=True, help_text='Upload your main invitation image designed in Canva (or another tool).', null=True, upload_to='invitation_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('baptism', 'Baptism'), ('image_upload', 'Image Upload Only')], default='wedding', help_text='The type of event being planned.', max_length=20),
        ),
    ]
