# Generated by Django 5.1.7 on 2025-08-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0004_event_main_invitation_image_alter_event_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('max_guests', models.PositiveIntegerField(default=0, help_text='Maximum number of guests allowed. Use a very large number for unlimited.')),
                ('has_table_assignment', models.BooleanField(default=False, help_text='Does this plan include the table assignment feature?')),
                ('can_upload_own_design', models.BooleanField(default=False, help_text='Does this plan allow uploading a custom design image?')),
            ],
        ),
    ]
