# Generated by Django 5.1.7 on 2025-08-26 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='color_class',
            field=models.CharField(blank=True, help_text="Main Tailwind CSS accent color. e.g., 'text-indigo-500'", max_length=50),
        ),
        migrations.AddField(
            model_name='plan',
            name='featured',
            field=models.BooleanField(default=False, help_text='Check this to make the plan stand out visually.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='icon_svg_path',
            field=models.TextField(blank=True, help_text="Paste the SVG <path> data for an icon here. e.g., <path d='...'/>"),
        ),
    ]
