# Generated by Django 5.1.7 on 2025-09-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0008_carddesign_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_events',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of events this plan allows.'),
        ),
    ]
