# Generated by Django 5.1.7 on 2025-09-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0009_plan_max_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audio_greeting',
            field=models.FileField(blank=True, help_text='Optional: Upload an audio greeting (e.g., MP3, M4A, WAV).', null=True, upload_to='audio_greetings/'),
        ),
    ]
