# Generated by Django 5.1.7 on 2025-09-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0010_event_audio_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='lock_event_on_creation',
            field=models.BooleanField(default=False, help_text='If True, events created under this plan cannot be edited or deleted.'),
        ),
    ]
