# Generated by Django 5.1.7 on 2025-09-09 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0011_plan_lock_event_on_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableassignment',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invapp.event'),
        ),
    ]
