# Generated by Django 5.1.7 on 2025-09-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0012_tableassignment_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesign',
            name='available_on_plans',
            field=models.ManyToManyField(blank=True, help_text='Select which subscription plans can use this design.', related_name='card_designs', to='invapp.plan'),
        ),
    ]
