# Generated by Django 5.1.7 on 2025-09-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0013_carddesign_available_on_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesign',
            name='special_field_name',
            field=models.CharField(blank=True, help_text="Optional: The name of the special model field this design requires (e.g., 'couple_photo').", max_length=100, null=True),
        ),
    ]
