# Generated by Django 5.1.7 on 2025-09-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0014_carddesign_special_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The exact field name from the Event model (e.g., 'couple_photo').", max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='A user-friendly description for the admin panel.', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='carddesign',
            name='special_field_name',
        ),
        migrations.AddField(
            model_name='carddesign',
            name='special_fields',
            field=models.ManyToManyField(blank=True, help_text='Select any special form fields this design requires.', related_name='card_designs', to='invapp.specialfield'),
        ),
    ]
