# Generated by Django 5.1.7 on 2025-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0015_specialfield_remove_carddesign_special_field_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Maps_embed_url',
        ),
        migrations.AddField(
            model_name='event',
            name='ceremony_maps_url',
            field=models.URLField(blank=True, help_text='The Google Maps URL for the CEREMONY location.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='party_maps_url',
            field=models.URLField(blank=True, help_text='The Google Maps URL for the PARTY location.', max_length=1000, null=True),
        ),
    ]
