# Generated by Django 5.1.7 on 2025-09-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0017_remove_event_ceremony_maps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ceremony_maps_url',
            field=models.URLField(blank=True, help_text='Optional: Google Maps Embed SRC URL', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='party_maps_url',
            field=models.URLField(blank=True, help_text='Optional: Google Maps Embed SRC URL', max_length=1000, null=True),
        ),
    ]
