# Generated by Django 5.1.7 on 2025-10-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0018_event_ceremony_maps_url_event_party_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='The Price ID from Stripe for this plan (e.g., price_1J...).', max_length=100),
        ),
    ]
