# Generated by Django 5.1.7 on 2025-10-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0019_plan_stripe_price_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='gender',
        ),
        migrations.AddField(
            model_name='guest',
            name='honorific',
            field=models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('family', 'The'), ('couple', 'The'), ('none', 'None')], default='none', help_text='The courtesy title for addressing the guest (e.g., Mr., Mrs., Family).', max_length=10),
        ),
    ]
