# Generated by Django 5.1.7 on 2025-10-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0020_remove_guest_gender_guest_honorific'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='honorific',
            field=models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('family', 'Family'), ('couple', 'Couple'), ('none', 'None')], default='none', help_text='The courtesy title for addressing the guest (e.g., Mr., Mrs., Family).', max_length=10),
        ),
    ]
