# Generated by Django 5.1.7 on 2025-10-21 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0021_alter_guest_honorific'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='godparents_names',
        ),
        migrations.CreateModel(
            name='Godparent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Full name of the godparent or godparent couple (e.g., 'John & Jane Smith').", max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godparents', to='invapp.event')),
            ],
        ),
    ]
