# Generated by Django 5.2.8 on 2025-11-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0022_remove_event_godparents_names_godparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='invitation_method',
            field=models.CharField(blank=True, choices=[('digital', 'Digital Invitation'), ('physical', 'Physical Invitation')], default='physical', max_length=20, null=True),
        ),
    ]
