# Generated by Django 5.2.8 on 2025-11-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0023_alter_guest_invitation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='party_time',
            field=models.TimeField(blank=True, help_text='Time of the religious ceremony (for baptism/wedding).', null=True, verbose_name='Ceremony Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Maps_embed_url',
            field=models.TextField(blank=True, help_text='Optional: Google Maps Embed SRC URL', null=True, verbose_name='Map Embed URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='audio_greeting',
            field=models.FileField(blank=True, help_text='Optional: Upload an audio greeting (e.g., MP3, M4A, WAV).', null=True, upload_to='audio_greetings/', verbose_name='Audio Greeting'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bride_name',
            field=models.CharField(blank=True, help_text='Name of the bride.', max_length=100, verbose_name='Bride Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bride_parents',
            field=models.CharField(blank=True, help_text="Names of the bride's parents (e.g., 'John & Jane Doe').", max_length=200, verbose_name="Bride's Parents"),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar_description',
            field=models.TextField(blank=True, help_text='Optional: Short description for calendar event', null=True, verbose_name='Calendar Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ceremony_location',
            field=models.CharField(blank=True, help_text='Name and address of the church/ceremony location.', max_length=255, verbose_name='Ceremony Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ceremony_maps_url',
            field=models.URLField(blank=True, help_text='Optional: Google Maps Embed SRC URL', max_length=1000, null=True, verbose_name='Ceremony Map Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ceremony_time',
            field=models.TimeField(blank=True, help_text='Time of the religious ceremony (for baptism/wedding).', null=True, verbose_name='Ceremony Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='child_name',
            field=models.CharField(blank=True, help_text='Name of the child (for baptism).', max_length=200, verbose_name='Child Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='couple_photo',
            field=models.ImageField(blank=True, help_text='A photo of the couple to be displayed on the invitation.', null=True, upload_to='event_photos/', verbose_name='Couple Photo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_time',
            field=models.DateTimeField(blank=True, help_text='Date and time of the event', null=True, verbose_name='Date & Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('baptism', 'Baptism'), ('image_upload', 'Image Upload Only')], default='wedding', help_text='The type of event being planned.', max_length=20, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='groom_name',
            field=models.CharField(blank=True, help_text='Name of the groom.', max_length=100, verbose_name='Groom Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='groom_parents',
            field=models.CharField(blank=True, help_text="Names of the groom's parents (e.g., 'George & Mary Smith').", max_length=200, verbose_name="Groom's Parents"),
        ),
        migrations.AlterField(
            model_name='event',
            name='invitation_wording',
            field=models.TextField(blank=True, help_text="Main invitation text (e.g., 'Together with their families...')", null=True, verbose_name='Invitation Wording'),
        ),
        migrations.AlterField(
            model_name='event',
            name='landscape_photo',
            field=models.ImageField(blank=True, help_text='Optional: A landscape-oriented photo to display after the greeting (e.g., a photo of the venue or couple).', null=True, upload_to='event_landscape_photos/', verbose_name='Landscape Photo'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_invitation_image',
            field=models.ImageField(blank=True, help_text='Upload your main invitation image designed in Canva (or another tool).', null=True, upload_to='invitation_images/', verbose_name='Main Invitation Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='other_info',
            field=models.TextField(blank=True, help_text='Other information (e.g., Dress code, Gift registry)', null=True, verbose_name='Other Information'),
        ),
        migrations.AlterField(
            model_name='event',
            name='parents_names',
            field=models.CharField(blank=True, help_text='Names of the parents (for baptism).', max_length=200, verbose_name="Parents' Names"),
        ),
        migrations.AlterField(
            model_name='event',
            name='party_maps_url',
            field=models.URLField(blank=True, help_text='Optional: Google Maps Embed SRC URL', max_length=1000, null=True, verbose_name='Party Map Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='schedule_details',
            field=models.TextField(blank=True, help_text='Details about the schedule (e.g., Ceremony, Reception times)', null=True, verbose_name='Schedule Details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Our Wedding', max_length=200, verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.TextField(blank=True, help_text='Full address of the venue', null=True, verbose_name='Venue Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, help_text='Name of the venue', max_length=200, null=True, verbose_name='Venue Name'),
        ),
    ]
