# Generated by Django 5.2.8 on 2025-11-29 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0024_event_party_time_alter_event_maps_embed_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of the event', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='party_time',
            field=models.TimeField(blank=True, help_text='Time when party starts.', null=True, verbose_name='Party Time'),
        ),
    ]
