# Generated by Django 5.2.8 on 2025-11-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0025_remove_event_date_time_event_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesign',
            name='is_multilanguage',
            field=models.BooleanField(default=False, help_text='Check if this design supports multiple languages (shows tick icon).'),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Higher numbers appear first in the carousel.'),
        ),
    ]
