# Generated by Django 5.2.8 on 2025-12-01 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0026_carddesign_is_multilanguage_carddesign_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Time')),
                ('activity_type', models.CharField(choices=[('civil_ceremony', 'Civil Ceremony'), ('religious_ceremony', 'Religious Ceremony'), ('reception', 'Reception'), ('party', 'Party'), ('photoshoot', 'Photoshoot'), ('other', 'Other')], default='civil_ceremony', max_length=50, verbose_name='Activity Type')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Location')),
                ('description', models.TextField(blank=True, help_text='Optional details about this part of the event.', verbose_name='Details')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='invapp.event')),
            ],
            options={
                'verbose_name': 'Schedule Item',
                'verbose_name_plural': 'Schedule Items',
                'ordering': ['time'],
            },
        ),
    ]
