# Generated by Django 5.2.8 on 2025-12-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0027_scheduleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesign',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If unchecked, this design is hidden from the public gallery but can still be assigned by admins for testing.'),
        ),
    ]
