# Generated by Django 5.2.8 on 2025-12-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0028_carddesign_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck this to hide the plan from the landing page (useful for Admin-only testing plans).'),
        ),
    ]
