# Generated by Django 5.2.8 on 2025-12-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0029_plan_is_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
