# Generated by Django 5.2.8 on 2025-12-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0030_faq_testimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['order'], 'verbose_name': 'FAQ Item'},
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, verbose_name='Answer (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Question (EN)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Răspuns (RO)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Ordinea de afișare'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Întrebare (RO)'),
        ),
    ]
