# Generated by Django 5.2.8 on 2025-12-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0031_delete_testimonial_alter_faq_options_faq_answer_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
