# Generated by Django 5.2.8 on 2025-12-25 08:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0032_testimonial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Review Client', 'verbose_name_plural': 'Reviews Clienți'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Este vizibil public?'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Nume Client'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Apare pe prima pagină?'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(default=5, help_text='Număr stele (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(blank=True, verbose_name='Mesaj (Opțional)'),
        ),
    ]
