# Generated by Django 5.2.8 on 2025-12-26 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0033_alter_testimonial_options_testimonial_avatar_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('hero_bg', 'Hero Background (Landing)'), ('logo_main', 'Logo Principal'), ('feature_1', 'Imagine Feature 1'), ('feature_2', 'Imagine Feature 2'), ('feature_3', 'Imagine Feature 3'), ('cta_bg', 'Call to Action Background')], help_text='Locul unde va apărea această imagine.', max_length=50, unique=True)),
                ('image', models.ImageField(help_text='Încarcă imaginea aici.', upload_to='site_assets/')),
                ('description', models.CharField(blank=True, help_text='Descriere pentru Alt Text (SEO)', max_length=200)),
            ],
        ),
    ]
