# Generated by Django 5.2.8 on 2025-12-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0034_siteimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddesign',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Admin control: Uncheck to soft-delete/hide this design everywhere.'),
        ),
        migrations.AddField(
            model_name='carddesign',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Upload a mockup image here (Cloudinary).', null=True, upload_to='design_previews/'),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If unchecked, this design is hidden from the public gallery.'),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='preview_image_path',
            field=models.CharField(blank=True, help_text='Path to preview image in static files (Legacy)', max_length=255, null=True),
        ),
    ]
