# Generated by Django 5.2.8 on 2025-12-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0035_carddesign_is_active_carddesign_preview_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='social_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook')], default='email', max_length=20, verbose_name='Sursa Review'),
        ),
    ]
