# Generated by Django 5.2.8 on 2026-01-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0036_testimonial_social_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='Maps_embed_url',
        ),
    ]
