# Generated by Django 5.2.8 on 2026-01-05 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0037_remove_event_maps_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ro', models.CharField(default='Creat cu Dragoste', max_length=200, verbose_name='Titlu (RO)')),
                ('description_ro', models.TextField(help_text='Textul principal în Română.', verbose_name='Descriere (RO)')),
                ('title_en', models.CharField(blank=True, default='Crafted with Love', max_length=200, verbose_name='Titlu (EN)')),
                ('description_en', models.TextField(blank=True, help_text='Textul principal în Engleză.', verbose_name='Descriere (EN)')),
                ('icon_svg_path', models.TextField(blank=True, help_text='Paste the SVG <path> data here.')),
                ('color_class', models.CharField(default='text-indigo-600', help_text='Tailwind color class for the icon (e.g., text-indigo-600, text-pink-500).', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section Configuration',
                'verbose_name_plural': 'About Section Configurations',
            },
        ),
        migrations.CreateModel(
            name='FutureFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ro', models.CharField(max_length=200, verbose_name='Titlu Funcționalitate (RO)')),
                ('description_ro', models.TextField(blank=True, verbose_name='Descriere Scurtă (RO)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Titlu Funcționalitate (EN)')),
                ('description_en', models.TextField(blank=True, verbose_name='Descriere Scurtă (EN)')),
                ('icon_svg_path', models.TextField(blank=True, help_text="Paste the SVG <path> data here (e.g., <path d='...'/>).")),
                ('color_class', models.CharField(default='text-indigo-600', help_text='Tailwind color class for the icon wrapper (e.g., text-indigo-600).', max_length=50)),
                ('target_date', models.DateField(blank=True, help_text='Internal target date for completion (Month/Year). Not necessarily shown publicly.', null=True)),
                ('is_public', models.BooleanField(default=True, help_text="Show this in the 'Coming Soon' section on the landing page?")),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher numbers appear first.')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='show_watermark',
            field=models.BooleanField(default=False, help_text="Dacă este bifat, afișează 'InvApp Demo' pe invitație (pentru planul Gratuit)."),
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ro', models.CharField(max_length=255, verbose_name='Text Funcționalitate (RO)')),
                ('text_en', models.CharField(blank=True, max_length=255, verbose_name='Text Funcționalitate (EN)')),
                ('is_included', models.BooleanField(default=True, help_text='Dacă este bifat, apare cu verde (inclus). Dacă nu, apare tăiat sau gri.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordinea de afișare în listă.')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='invapp.plan')),
            ],
            options={
                'verbose_name': 'Plan Feature',
                'verbose_name_plural': 'Plan Features',
                'ordering': ['order'],
            },
        ),
    ]
