# Generated by Django 5.2.8 on 2026-01-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0038_aboutsection_futurefeature_plan_show_watermark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='show_watermark',
            field=models.BooleanField(default=True, help_text='If is checked, invites from these plan will have watermark.', verbose_name='Show Watermark'),
        ),
    ]
