# Generated by Django 5.2.8 on 2026-02-22 13:25

import cloudinary.models
import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0040_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'Customer Review', 'verbose_name_plural': 'Customer Reviews'},
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_en',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_en',
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ro',
            field=models.TextField(blank=True, verbose_name='Answer (RO)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ro',
            field=models.CharField(blank=True, max_length=255, verbose_name='Question (RO)'),
        ),
        migrations.AddField(
            model_name='guest',
            name='preferred_language',
            field=models.CharField(choices=[('ro', 'Romanian'), ('en', 'English')], default='ro', help_text='The language in which the guest will see the digital invitation.', max_length=5, verbose_name='Preferred Language'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description_en',
            field=models.TextField(help_text='Main text in English.', verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description_ro',
            field=models.TextField(blank=True, help_text='Main text in Romanian.', verbose_name='Description (RO)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(default='Crafted with Love', max_length=200, verbose_name='Title (EN)'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_ro',
            field=models.CharField(blank=True, default='Creat cu Dragoste', max_length=200, verbose_name='Title (RO)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='audio_greeting',
            field=models.FileField(blank=True, help_text='Optional: Upload an audio greeting (e.g., MP3, M4A, WAV).', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='audio_greetings/', verbose_name='Audio Greeting'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='Answer (EN)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255, verbose_name='Question (EN)'),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Short Description (EN)'),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='description_ro',
            field=models.TextField(blank=True, verbose_name='Short Description (RO)'),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='title_en',
            field=models.CharField(max_length=200, verbose_name='Feature Title (EN)'),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='title_ro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Feature Title (RO)'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='Recommended format: JPG/PNG. Maximum 5MB.', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='show_watermark',
            field=models.BooleanField(default=True, help_text='If checked, invites from this plan will have a watermark.', verbose_name='Show Watermark'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='is_included',
            field=models.BooleanField(default=True, help_text='If checked, it appears in green (included). If not, it appears struck through or gray.'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in the list.'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Feature Text (EN)'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='text_ro',
            field=models.CharField(max_length=255, verbose_name='Feature Text (RO)'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='description',
            field=models.CharField(blank=True, help_text='Description for Alt Text (SEO)', max_length=200),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=models.ImageField(help_text='Upload image here.', upload_to='site_assets/'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='key',
            field=models.CharField(choices=[('hero_bg', 'Hero Background (Landing)'), ('logo_main', 'Primary Logo'), ('feature_1', 'Feature Image 1'), ('feature_2', 'Feature Image 2'), ('feature_3', 'Feature Image 3'), ('cta_bg', 'Call to Action Background'), ('partner_promo', 'Partner Promotion (Culori)')], help_text='Where this image will appear.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(max_length=100, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is visible publicly?'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Appears on home page?'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(default=5, help_text='Star rating (1-5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='social_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook')], default='email', max_length=20, verbose_name='Review Source'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(blank=True, verbose_name='Message (Optional)'),
        ),
    ]
