# Generated by Django 5.2.8 on 2026-02-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0041_alter_testimonial_options_remove_faq_answer_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ceremony_address',
            field=models.TextField(blank=True, help_text='Full address of the ceremony location', null=True, verbose_name='Ceremony Address'),
        ),
    ]
