# Generated by Django 5.2.8 on 2026-02-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0042_event_ceremony_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ceremony_address',
            field=models.TextField(blank=True, help_text='Physical address of the ceremony.', null=True, verbose_name='Ceremony Address'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ceremony_location',
            field=models.CharField(blank=True, help_text="Name of the church or ceremony location (e.g. 'St. Nicholas Church').", max_length=255, verbose_name='Ceremony Venue Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='ceremony_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps Link. This will be embedded as an interactive map in your invitation.', max_length=1000, null=True, verbose_name='Ceremony Map Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='party_maps_url',
            field=models.URLField(blank=True, help_text='Google Maps Link. This will be embedded as an interactive map in your invitation.', max_length=1000, null=True, verbose_name='Party Map Link'),
        ),
    ]
