# Generated by Django 5.2.8 on 2026-02-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0043_alter_event_ceremony_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteimage',
            name='key',
            field=models.CharField(choices=[('hero_bg', 'Hero Background (Landing)'), ('global_bg', 'Global Site Background'), ('logo_main', 'Primary Logo'), ('feature_1', 'Feature Image 1'), ('feature_2', 'Feature Image 2'), ('feature_3', 'Feature Image 3'), ('cta_bg', 'Call to Action Background'), ('partner_promo', 'Partner Promotion (Culori)')], help_text='Where this image will appear.', max_length=50, unique=True),
        ),
    ]
