# Generated by Django 5.2.8 on 2026-02-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0044_alter_siteimage_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='invitation_method',
            field=models.CharField(blank=True, choices=[('digital', 'Digital'), ('physical', 'On Paper')], default='physical', max_length=20, null=True),
        ),
    ]
