# Generated by Django 5.2.8 on 2026-02-24 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0045_alter_guest_invitation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='manual_attending_count',
            field=models.PositiveIntegerField(blank=True, help_text='Manually set number of attendees if known (especially for paper RSVPs).', null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='manual_is_attending',
            field=models.BooleanField(blank=True, help_text='Manually set attendance status (e.g., for paper RSVPs).', null=True),
        ),
    ]
