# Generated by Django 5.2.8 on 2026-02-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0046_alter_guest_manual_attending_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='rsvp_source',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic (Guest)'), ('manual', 'Manual (Host)')], default='manual', help_text='Indicates if the RSVP was confirmed digitally by the guest or manually by the host.', max_length=20, null=True),
        ),
    ]
