# Generated by Django 5.2.8 on 2026-02-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0047_guest_rsvp_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='rsvp_source',
            field=models.CharField(blank=True, choices=[('automatic', 'Automat (Invitat)'), ('manual', 'Manual (Gazdă)')], default='manual', help_text='Indicates if the RSVP was confirmed digitally by the guest or manually by the host.', max_length=20, null=True),
        ),
    ]
