# Generated by Django 5.2.8 on 2026-02-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0050_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='campaign_name',
            field=models.CharField(blank=True, help_text='Ex: Targ_Nunti_Februarie_2026', max_length=100),
        ),
        migrations.AddField(
            model_name='voucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='used_by',
            field=models.CharField(blank=True, help_text='Email of the user who used this voucher.', max_length=255),
        ),
        migrations.AddField(
            model_name='voucher',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
