# Generated by Django 5.2.8 on 2026-02-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0051_voucher_campaign_name_voucher_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, help_text='If empty, the voucher applies to ALL plans.', to='invapp.plan'),
        ),
    ]
