# Generated by Django 5.2.8 on 2026-02-25 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0052_voucher_applicable_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal name for this campaign (e.g. 'Wedding Fair Feb')", max_length=100)),
                ('is_active', models.BooleanField(default=False, help_text='Only one campaign can be active at a time.')),
                ('show_urgency_bar', models.BooleanField(default=False)),
                ('urgency_text', models.CharField(blank=True, help_text='Text shown in the top banner.', max_length=255)),
                ('countdown_end_date', models.DateTimeField(blank=True, help_text='The countdown will run until this date.', null=True)),
                ('hero_headline', models.CharField(help_text='Main title on the landing page.', max_length=200)),
                ('hero_subheadline', models.TextField(blank=True, help_text='Supporting text below the headline.')),
                ('primary_button_text', models.CharField(default='Start Now', max_length=50)),
                ('primary_button_link', models.CharField(default='/ro/accounts/signup/', max_length=200)),
                ('theme_color_hex', models.CharField(default='#4f46e5', help_text='Primary accent color hex code.', max_length=7)),
            ],
            options={
                'verbose_name': 'Marketing Campaign',
                'verbose_name_plural': 'Marketing Campaigns',
            },
        ),
    ]
