# Generated by Django 5.2.8 on 2026-02-25 09:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0053_marketingcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Voucher becomes active from this date.'),
        ),
    ]
