# Generated by Django 5.2.8 on 2026-02-25 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0054_voucher_valid_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Partner Name')),
                ('whatsapp_number', models.CharField(help_text="International format without '+' (e.g., 40712345678)", max_length=20, verbose_name='WhatsApp Number')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('website_url', models.URLField(blank=True, verbose_name='Website URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Platform Partner',
                'verbose_name_plural': 'Platform Partners',
            },
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='The partner associated with this campaign.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invapp.platformpartner'),
        ),
    ]
