# Generated by Django 5.2.8 on 2026-02-25 13:29

import cloudinary.models
import cloudinary_storage.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0055_platformpartner_marketingcampaign_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='custom_message',
            field=models.TextField(blank=True, help_text='Optional custom message for WhatsApp sharing.'),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='color_class',
            field=models.CharField(default='text-indigo-600', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='description_ro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='icon_svg_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_en',
            field=models.CharField(default='Crafted with Love', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='title_ro',
            field=models.CharField(blank=True, default='Created with Love', max_length=200),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='available_on_plans',
            field=models.ManyToManyField(blank=True, related_name='card_designs', to='invapp.plan'),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('baptism', 'Baptism'), ('image_upload', 'Image Upload Only')], default='wedding', max_length=20),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='is_multilanguage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='design_previews/'),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='preview_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='special_fields',
            field=models.ManyToManyField(blank=True, related_name='card_designs', to='invapp.specialfield'),
        ),
        migrations.AlterField(
            model_name='carddesign',
            name='template_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='audio_greeting',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='audio_greetings/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bride_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='bride_parents',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='calendar_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ceremony_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ceremony_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='event',
            name='ceremony_maps_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ceremony_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='child_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='couple_photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('wedding', 'Wedding'), ('baptism', 'Baptism'), ('image_upload', 'Image Upload Only')], default='wedding', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='groom_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='groom_parents',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='invitation_wording',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='landscape_photo',
            field=models.ImageField(blank=True, null=True, upload_to='event_landscape_photos/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='main_invitation_image',
            field=models.ImageField(blank=True, null=True, upload_to='invitation_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='other_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='parents_names',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='party_maps_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='party_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='schedule_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='Our Wedding', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='color_class',
            field=models.CharField(default='text-indigo-600', max_length=50),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='description_ro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='icon_svg_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='target_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='futurefeature',
            name='title_ro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='godparent',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='honorific',
            field=models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('family', 'Family'), ('couple', 'Couple'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='guest',
            name='manual_attending_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='manual_is_attending',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='max_attendees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='guest',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='preferred_language',
            field=models.CharField(choices=[('ro', 'Romanian'), ('en', 'English')], default='ro', max_length=5),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_source',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic (Guest)'), ('manual', 'Manual (Host)')], default='manual', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='countdown_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='hero_headline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='hero_subheadline',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invapp.platformpartner'),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='theme_color_hex',
            field=models.CharField(default='#4f46e5', max_length=7),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='urgency_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='plan',
            name='can_upload_own_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='color_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='plan',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='has_table_assignment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='icon_svg_path',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='lock_event_on_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_events',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='show_watermark',
            field=models.BooleanField(default=True, verbose_name='Show Watermark'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='is_included',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platformpartner',
            name='whatsapp_number',
            field=models.CharField(max_length=20, verbose_name='WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='attending',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='meal_preference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='number_attending',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='activity_type',
            field=models.CharField(choices=[('civil_ceremony', 'Civil Ceremony'), ('religious_ceremony', 'Religious Ceremony'), ('reception', 'Reception'), ('party', 'Party'), ('photoshoot', 'Photoshoot'), ('other', 'Other')], default='civil_ceremony', max_length=50),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='image',
            field=models.ImageField(upload_to='site_assets/'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='key',
            field=models.CharField(choices=[('hero_bg', 'Hero Background (Landing)'), ('global_bg', 'Global Site Background'), ('logo_main', 'Primary Logo'), ('feature_1', 'Feature Image 1'), ('feature_2', 'Feature Image 2'), ('feature_3', 'Feature Image 3'), ('cta_bg', 'Call to Action Background'), ('partner_promo', 'Partner Promotion (Culori)')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='specialfield',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='specialfield',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='social_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, to='invapp.plan'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='used_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
