# Generated by Django 5.2.8 on 2026-02-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invapp', '0056_voucher_custom_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='host_whatsapp',
            field=models.CharField(blank=True, help_text="Format: 407XXXXXXXX (no '+' or '0' in front)", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='whatsapp_custom_message',
            field=models.CharField(blank=True, help_text='Default pre-filled message for the guest to send to the host.', max_length=255, null=True),
        ),
    ]
